// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wahdjskwegycbrxiyjjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhaGRqc2t3ZWd5Y2JyeGl5ampnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1Nzk4NTMsImV4cCI6MjA3NTE1NTg1M30._dfqI8RLWTjMS-hdPsynCAiy-wTd_czWvyqK6XSKyUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});